---
- hosts: localhost
  connection: local

  vars_files:
  - group_vars/all

  - name: decommission shellshock instances
    ec2:
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{ ec2_secret_key }}"
      count_tag:
        Name: demo_jbersuder_shellshock
      exact_count: 0
      state: stopped

