---
- name: terminate hosts
  hosts: "{{ ec2_hosts }}" 
  gather_facts: false
  connection: local  

  vars:
    ec2_hosts: tag_Name_demo_{{ tower_user_name }}_windows

  tasks:
  - name: terminate EC2 hosts
    hosts: localhost
    connection: local
    ec2: >
      region="{{ ec2_region }}"
      instance_ids="{{ item }}"
      state=absent
      wait=True
    with_items: "{{hostvars[inventory_hostname]['ec2_id']}}"

