---
- hosts: localhost
  connection: local

  tasks:
  - name: remote facts
    ec2_remote_facts:

  - name: terminate hosts
    local_action:
      module: ec2
      instance_tags:
        Name: "demo_{{ tower_user_name }}_windows"
      state: absent

