---
- hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: remote facts
    connection: local
    ec2_remote_facts:

  - name: terminate hosts
    local_action: ec2 instance_tags=Name: "demo_{{ tower_user_name }}_windows"
      state: absent

