---
- name: gather EC2 facts
  hosts: "{{ ec2_hosts }}"
  gather_facts: false 

  vars:
    ec2_region: us-east-1
    ec2_hosts: tag_Name_demo_{{ tower_user_name }}_shellshock

<<<<<<< HEAD
  tasks:
  - name: gather facts 
    ec2_facts:

- name: terminate hosts
  hosts: "{{ ec2_hosts }}"
  gather_facts: false
  connection: local  

  vars:
    ec2_hosts: tag_Name_demo_{{ tower_user_name }}_shellshock

  tasks:
  - name: terminate EC2 hosts
    ec2: >
      region="{{ ec2_region }}"
      instance_ids="{{ item }}"
      state=absent
      wait=True
    with_items: hostvars[inventory_hostname]['ansible_ec2_instance_id'] 
=======
  - name: decommission shellshock instances
    ec2:
      aws_access_key: "{{ ec2_access_key }}"
      aws secret_key: "{{ ec2_secret_key }}"
      count_tag:
        Name: demo_jbersuder_shellshock
      state: stopped
>>>>>>> 51b8aae86c34f9137c8671366cd40dfaf1b4de38

