---
- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - group_vars/all

  tasks:
    - name: Terminate instances 
      local_action: ec2
        state='absent'
        instance_ids='{{ ec2_id }}'
        region='{{ ec2_region }}'
        wait=True
