---
- hosts: tag_Name_demo_{{ tower_user_name }}_windows
  connection: local
  tasks:
  - ec2:
      state: absent
      region: us-west-2
      instance_ids: "{{ item }}"
    with_items: "{{hostvars[inventory_hostname]['ec2_id']}}" 
