---
- name: terminate hosts
  hosts: "{{ ec2_hosts }}" 
  gather_facts: false
  connection: local  

  vars:
    ec2_region: us-east-1
    ec2_hosts: tag_Name_demo_{{ tower_user_name }}_shellshock

  tasks:
  - ec2_facts
  - ec2: 
     region: "{{ ec2_region }}"
     instance_ids: "{{ item }}"
     state: absent
     wait: True
    with_items: "{{ ec2_hosts }}"

