---
- hosts: all
  gather_facts: true

  tasks:
    - name: creating inventory_dir
      file: path=/tmp/inventory state=directory mode=0755

    - name: write host info to file
      shell: 'uname -a ; cat /etc/resolv.conf'
      register: Host_Info
    - debug: var=Host_Info
    - name: write to file
      shell:  "cat {{ Host_Info.stdout }} > /tmp/inventory/host-info.txt"
