---
# Provision instances for the Shellshock demo:
- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
  - group_vars/eu-1
 
 # Tag the instances with the username of the Tower user
  tasks:
  - name: remove training instances
    ec2: >
     access_key="{{ ec2_access_key }}"
     secret_key="{{ ec2_secret_key }}"
     region="{{ ec2_region }}"
     wait=true
     state=stopped
